#!/usr/bin/env bash
set -eu

# idempotent buildroot manager

br_version_default=2022.11
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
time=$(cat "${script_dir}/configs/time")
directory=.

positional_args=()

while [[ $# -gt 0 ]]; do
  case $1 in
  -C | --directory)
    directory="$2"
    shift # past argument
    shift # past value
    ;;
  -*)
    echo "Unknown option $1"
    exit 1
    ;;
  *)
    positional_args+=("$1") # save positional arg
    shift                   # past argument
    ;;
  esac
done

set -- "${positional_args[@]}" # restore positional parameters

directory=$(realpath "${directory}")
external_dir=${directory}/external
builds_dir=${directory}/builds

_workspace() {
    local external_dir=${1}
    local builds_dir=${2}
    mkdir -p "${external_dir}"
    mkdir -p "${builds_dir}"
}

_archive() {
    local external_dir=${1}
    local br_version=${2}
    echo "${external_dir}/buildroot-${br_version}.tar.xz"
}

_build_dir() {
    local builds_dir=${1}
    local br_version=${2}
    echo "${builds_dir}/buildroot-${br_version}"
}
_check_xz() {
    local file=${1}
    xz -t "${file}"
}

_fetch() {
    local br_version=${1}
    local archive=${2}
    local build_dir=${3}
    br_source=https://buildroot.org/downloads/buildroot-${br_version}.tar.xz
    _check_xz "${archive}" || wget "${br_source}" -O "${archive}"
    mkdir -p "${build_dir}"
    tar -xf "${archive}" --strip-components=1 -C "${build_dir}" 
}

_generate() {
    local build_dir=${1}
    local config=${2}
    local defconfig=custom_${config}_defconfig
    local out_dir=${directory}/builds/${config}
    cp "${directory}/configs/${defconfig}" "${build_dir}/configs/${defconfig}"
    workdir=$(pwd)
    mkdir -p "${out_dir}"
    cd "${build_dir}"
    make "${defconfig}" "O=${out_dir}"
    make "O=${out_dir}"
    cd "${workdir}"
}

br_version=${br_version_default}
archive=$(_archive ${external_dir} ${br_version})
build_dir=$(_build_dir ${builds_dir} ${br_version})

_workspace "${external_dir}" "${builds_dir}"
_fetch "${br_version}" "${archive}" "${build_dir}"
_generate "${build_dir}" "${1}"